name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api-version: 1.13
soft-depend:
  - PlaceholderAPI
depend:
  - ProtocolLib
commands:
  swiftboard:
    description: "Manage SwiftBoard"